[package]
name = "budget_gba"
version = "0.1.0"
edition = "2024"

[dependencies]
bitfield-struct = "0.11"
num-traits = "0.2.19"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0"
